In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('PPFCF_PPFAS_Monthly_Portfolio_Report_September_30_2024.xls')

In [5]:
df

,Unnamed: 0,"Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Monthly Portfolio Statement as on September 30...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Name of the Instrument,ISIN,Industry / Rating,Quantity,Market/Fair Value\n (Rs. in Lakhs),% to Net\n Assets,YTM~,YTC^,NaN,NaN
3,NaN,Equity & Equity related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(a) Listed / awaiting listing on Stock Exchanges,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,NaN,Tier I Benchmark’s Risk-o-meter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,NaN,NIFTY 500 TRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
equity_domestic = 'Equity & Equity related'
arbitrage = 'Arbitrage'
unlisted = '(b) Unlisted'
equity_foreign = 'Equity & Equity related Foreign Investments'
derivatives = 'Derivatives'
money_market = 'Money Market Instruments'
options = ' '
futures = 'Index / Stock Futures'
end_note = 'Notes:'

In [119]:
def extract_statement_period(df):
    return df[df.iloc[:,1].astype('str').str.contains('Monthly Portfolio Statement')].iloc[:,1].values[0]

In [7]:
def get_idx_from_instrument_text(df, text, column=1):
    return df[df.iloc[:, column]==text].index[0]

In [84]:
def get_raw_table(df, start_idx_text, end_idx_text):
    start_idx = get_idx_from_instrument_text(df, start_idx_text)
    end_idx = get_idx_from_instrument_text(df, end_idx_text)
    table_df = df.iloc[start_idx:end_idx-1, :]
    return table_df

In [85]:
table_extract_combos = [(equity_domestic, arbitrage),(arbitrage, unlisted), (equity_foreign, options), (options,money_market), (money_market, futures),(futures,end_note)]

In [86]:
def extract_all_raw_tables(df, table_extract_combos):
    df_dict = {}
    for start, end in table_extract_combos:
        df_dict[start] = get_raw_table(df, start, end)
    return df_dict

In [120]:
statement_period = extract_statement_period(df)

In [87]:
df_dict = extract_all_raw_tables(df, table_extract_combos)

In [95]:
df_dict

{'Equity & Equity related':     Unnamed: 0  \
 3          NaN
 4          NaN
 5          NaN
 6          NaN
 7          NaN
 8          NaN
 9          NaN
 10         NaN
 11         NaN
 12         NaN
 13         NaN
 14         NaN
 15         NaN
 16         NaN
 17         NaN
 18         NaN
 19         NaN
 20         NaN
 21         NaN
 22         NaN
 23         NaN
 24         NaN
 25         NaN
 26         NaN
 27         NaN
 28         NaN
 29         NaN
 30         NaN
 31         NaN
 32         NaN
 33         NaN

    Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)  \
 3                             Equity & Equity related
 4    (a) Listed / awaiting listing on Stock Exchanges
 5                                   HDFC Bank Limited
 6             Power Grid Corporation of India Limited
 7                 Bajaj Holdings & Investment Limited
 8                                  Coal India Limited
 9                                         ITC Limited
 10                                 ICICI Bank Limited
 11                        Maruti Suzuki India Limited
 12                           HCL Technologies Limited
 13                                  Axis Bank Limited
 14                        Kotak Mahindra Bank Limited
 15           Motilal Oswal Financial Services Limited
 16                                    Infosys Limited
 17                      Balkrishna Industries Limited
 18          Multi Commodity Exchange of India Limited
 19                     Indian Energy Exchange Limited
 20        Central Depository Services (India) Limited
 21                         Zydus Lifesciences Limited
 22                   Dr. Reddy's Laboratories Limited
 23                                      Cipla Limited
 24                          IPCA Laboratories Limited
 25                           Indraprastha Gas Limited
 26                                       NMDC Limited
 27                                       ICRA Limited
 28                            EID Parry India Limited
 29               UTI Asset Management Company Limited
 30                       Maharashtra Scooters Limited
 31                             Swaraj Engines Limited
 32                    Accelya Solutions India Limited
 33                                                NaN

       Unnamed: 2                       Unnamed: 3 Unnamed: 4    Unnamed: 5  \
 3            NaN                              NaN        NaN           NaN
 4            NaN                              NaN        NaN           NaN
 5   INE040A01034                            Banks   38717754     670610.86
 6   INE752E01010                            Power  170268886     600793.76
 7   INE118A01012                          Finance    5276536     553756.62
 8   INE522F01014                 Consumable Fuels   97650994     498166.55
 9   INE154A01025                 Diversified FMCG   88311955     457588.39
 10  INE090A01021                            Banks   33093059     421274.64
 11  INE585B01010                      Automobiles    3043078     402842.67
 12  INE860A01027                    IT - Software   18706973     335995.94
 13  INE238A01034                            Banks   23645558     291360.57
 14  INE237A01028                            Banks   13141651     243639.64
 15  INE338I01027                  Capital Markets   22275986     169765.29
 16  INE009A01021                    IT - Software    8733754     163810.29
 17  INE787D01026                  Auto Components    4189074     127773.04
 18  INE745G01035                  Capital Markets    1871649     105940.95
 19  INE022Q01020                  Capital Markets   44206584      90305.21
 20  INE736A01011                  Capital Markets    6156590      88476.35
 21  INE010B01027  Pharmaceuticals & Biotechnology    7678847      82052.32
 22  INE089A01023  Pharmaceuticals & Biotechnology    1187695      80188.42
 23  INE059A01026  Pharmaceuticals & Biotechnology    4174123      69044.17
 24  INE571A01038  Pharmaceuticals & Biotechnology    3541831      53060.17
 25  INE203G01027                              Gas    9335026      52140.79
 26  INE584A01023                Minerals & Mining   17775934  43535.039959
 27  INE725G01011                  Capital Markets     422587      30585.58
 28  INE126A01031      Fertilizers & Agrochemicals    2259531      19381.13
 29  INE094J01016                  Capital Markets     962555      11929.43
 30  INE288A01013                          Finance      80159       9413.75
 31  INE277A01016              Industrial Products      47293       1514.49
 32  INE793A01012                    IT - Software      25272        473.17
 33           NaN                              NaN        NaN           NaN

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10
 3         NaN        NaN        NaN        NaN         NaN
 4         NaN        NaN        NaN        NaN         NaN
 5      0.0813        NaN        NaN        NaN         NaN
 6      0.0729        NaN        NaN        NaN         NaN
 7      0.0672        NaN        NaN        NaN         NaN
 8      0.0604        NaN        NaN        NaN         NaN
 9      0.0555        NaN        NaN        NaN         NaN
 10     0.0511        NaN        NaN        NaN         NaN
 11     0.0489        NaN        NaN        NaN         NaN
 12     0.0408        NaN        NaN        NaN         NaN
 13     0.0353        NaN        NaN        NaN         NaN
 14     0.0296        NaN        NaN        NaN         NaN
 15     0.0206        NaN        NaN        NaN         NaN
 16     0.0199        NaN        NaN        NaN         NaN
 17     0.0155        NaN        NaN        NaN         NaN
 18     0.0129        NaN        NaN        NaN         NaN
 19      0.011        NaN        NaN        NaN         NaN
 20     0.0107        NaN        NaN        NaN         NaN
 21       0.01        NaN        NaN        NaN         NaN
 22     0.0097        NaN        NaN        NaN         NaN
 23     0.0084        NaN        NaN        NaN         NaN
 24     0.0064        NaN        NaN        NaN         NaN
 25     0.0063        NaN        NaN        NaN         NaN
 26     0.0053        NaN        NaN        NaN         NaN
 27     0.0037        NaN        NaN        NaN         NaN
 28     0.0024        NaN        NaN        NaN         NaN
 29     0.0014        NaN        NaN        NaN         NaN
 30     0.0011        NaN        NaN        NaN         NaN
 31     0.0002        NaN        NaN        NaN         NaN
 32     0.0001        NaN        NaN        NaN         NaN
 33        NaN        NaN        NaN        NaN         NaN  ,
 'Arbitrage':     Unnamed: 0  \
 35         NaN
 36         NaN
 37         NaN
 38         NaN
 39         NaN
 40         NaN
 41         NaN
 42         NaN
 43         NaN
 44         NaN
 45         NaN
 46         NaN
 47         NaN
 48         NaN
 49         NaN
 50         NaN
 51         NaN
 52         NaN
 53         NaN
 54         NaN
 55         NaN
 56         NaN
 57         NaN
 58         NaN
 59         NaN

    Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)  \
 35                                          Arbitrage
 36                              Bajaj Finance Limited
 37                         Bharat Electronics Limited
 38                              IndusInd Bank Limited
 39                              Bharti Airtel Limited
 40                                Tata Motors Limited
 41                        Mahindra & Mahindra Limited
 42                        Hindalco Industries Limited
 43                               Bandhan Bank Limited
 44                                     Biocon Limited
 45                        Reliance Industries Limited
 46                                       NMDC Limited
 47                   Bharat Heavy Electricals Limited
 48                              Titan Company Limited
 49                                        DLF Limited
 50                                       IDFC Limited
 51                           Hindustan Copper Limited
 52                              PI Industries Limited
 53                                 Tata Steel Limited
 54                HDFC Life Insurance Company Limited
 55                       Jindal Steel & Power Limited
 56                              Bajaj Finserv Limited
 57                         Hindustan Unilever Limited
 58                            Larsen & Toubro Limited
 59                             United Spirits Limited

       Unnamed: 2                       Unnamed: 3 Unnamed: 4 Unnamed: 5  \
 35           NaN                              NaN        NaN        NaN
 36  INE296A01024                          Finance     372250   28674.42
 37  INE263A01024              Aerospace & Defense    1117200    3185.14
 38  INE095A01012                            Banks     207500    3003.77
 39  INE397D01024               Telecom - Services     166250    2842.13
 40  INE155A01022                      Automobiles     289850    2825.02
 41  INE101A01026                      Automobiles      76300    2361.41
 42  INE038A01020             Non - Ferrous Metals     306600    2318.51
 43  INE545U01014                            Banks     677600    1346.66
 44  INE376G01013  Pharmaceuticals & Biotechnology     367500    1334.39
 45  INE002A01018               Petroleum Products      41750    1232.94
 46  INE584A01023                Minerals & Mining     346500  848.61315
 47  INE257A01026             Electrical Equipment     228375     638.76
 48  INE280A01028                Consumer Durables      16100     615.66
 49  INE271C01023                           Realty      66825     598.18
 50  INE043D01016                          Finance     480000     543.79
 51  INE531E01026             Non - Ferrous Metals     124550     428.33
 52  INE603J01030      Fertilizers & Agrochemicals       5250     244.43
 53  INE081A01020                   Ferrous Metals      99000     166.86
 54  INE795G01014                        Insurance      19800     142.16
 55  INE749A01030                   Ferrous Metals       8750      90.97
 56  INE918I01026                          Finance       4500       88.8
 57  INE030A01027                 Diversified FMCG       2700      79.87
 58  INE018A01030                     Construction       1200      44.11
 59  INE854D01024                        Beverages       1400      22.26

    Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10
 35        NaN        NaN        NaN        NaN         NaN
 36     0.0035        NaN        NaN        NaN         NaN
 37     0.0004        NaN        NaN        NaN         NaN
 38     0.0004        NaN        NaN        NaN         NaN
 39     0.0003        NaN        NaN        NaN         NaN
 40     0.0003        NaN        NaN        NaN         NaN
 41     0.0003        NaN        NaN        NaN         NaN
 42     0.0003        NaN        NaN        NaN         NaN
 43     0.0002        NaN        NaN        NaN         NaN
 44     0.0002        NaN        NaN        NaN         NaN
 45     0.0001        NaN        NaN        NaN         NaN
 46     0.0001        NaN        NaN        NaN         NaN
 47     0.0001        NaN        NaN        NaN         NaN
 48     0.0001        NaN        NaN        NaN         NaN
 49     0.0001        NaN        NaN        NaN         NaN
 50     0.0001        NaN        NaN        NaN         NaN
 51     0.0001        NaN        NaN        NaN         NaN
 52     $0.00%        NaN        NaN        NaN         NaN
 53     $0.00%        NaN        NaN        NaN         NaN
 54     $0.00%        NaN        NaN        NaN         NaN
 55     $0.00%        NaN        NaN        NaN         NaN
 56     $0.00%        NaN        NaN        NaN         NaN
 57     $0.00%        NaN        NaN        NaN         NaN
 58     $0.00%        NaN        NaN        NaN         NaN
 59     $0.00%        NaN        NaN        NaN         NaN  ,
 'Equity & Equity related Foreign Investments':     Unnamed: 0  \
 64         NaN
 65         NaN
 66         NaN
 67         NaN
 68         NaN
 69         NaN
 70         NaN
 71         NaN
 72         NaN
 73         NaN

    Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)  \
 64        Equity & Equity related Foreign Investments
 65   (a) Listed / awaiting listing on Stock Exchanges
 66                 Meta Platforms Registered Shares A
 67                                     Microsoft Corp
 68                                     Alphabet Inc A
 69                                     Amazon Com Inc
 70                                          Sub Total
 71                                       (b) Unlisted
 72                                          Sub Total
 73                                              Total

       Unnamed: 2                                         Unnamed: 3  \
 64           NaN                                                NaN
 65           NaN                                                NaN
 66  US30303M1027  Computer Software: Programming, Data Processing #
 67  US5949181045          Computer Software: Prepackaged Software #
 68  US02079K3059  Computer Software: Programming, Data Processing #
 69  US0231351067                   Catalog/Specialty Distribution #
 70           NaN                                                NaN
 71           NaN                                                NaN
 72           NaN                                                NaN
 73           NaN                                                NaN

    Unnamed: 4  Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  \
 64        NaN         NaN        NaN        NaN        NaN        NaN
 65        NaN         NaN        NaN        NaN        NaN        NaN
 66     591056    283522.2     0.0344        NaN        NaN        NaN
 67     733019   264310.88     0.0321        NaN        NaN        NaN
 68    1879477   261204.68     0.0317        NaN        NaN        NaN
 69    1368668   213702.38     0.0259        NaN        NaN        NaN
 70        NaN  1022740.14     0.1241        NaN        NaN        NaN
 71        NaN         NIL        NIL        NaN        NaN        NaN
 72        NaN         NIL        NIL        NaN        NaN        NaN
 73        NaN  1022740.14     0.1241        NaN        NaN        NaN

    Unnamed: 10
 64         NaN
 65         NaN
 66         NaN
 67         NaN
 68         NaN
 69         NaN
 70         NaN
 71         NaN
 72         NaN
 73         NaN  ,
 'Index / Stock Options':     Unnamed: 0  \
 75         NaN
 76         NaN
 77         NaN

    Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)  \
 75                              Index / Stock Options
 76     Nifty 50 Index 22000 Call December 2024 Option
 77                                          Sub Total

    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
 75        NaN        NaN        NaN        NaN        NaN        NaN
 76        NaN                 51950    2157.72     0.0003        NaN
 77        NaN        NaN        NaN    2157.72     0.0003        NaN

    Unnamed: 8 Unnamed: 9 Unnamed: 10
 75        NaN        NaN         NaN
 76        NaN        NaN         NaN
 77        NaN        NaN         NaN  ,
 'Money Market Instruments':      Unnamed: 0  \
 79          NaN
 80          NaN
 81          NaN
 82          NaN
 83          NaN
 84          NaN
 85          NaN
 86          NaN
 87          NaN
 88          NaN
 89          NaN
 90          NaN
 91          NaN
 92          NaN
 93          NaN
 94          NaN
 95          NaN
 96          NaN
 97          NaN
 98          NaN
 99          NaN
 100         NaN
 101         NaN
 102         NaN
 103         NaN
 104         NaN
 105         NaN
 106         NaN
 107         NaN
 108         NaN
 109         NaN
 110         NaN
 111         NaN
 112         NaN
 113         NaN
 114         NaN
 115         NaN

     Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)  \
 79                            Money Market Instruments
 80                              Certificate of Deposit
 81                   Punjab National Bank (15/05/2025)
 82                            Canara Bank (02/09/2025)
 83                     ICICI Bank Limited (27/06/2025)
 84                    Union Bank of India (31/01/2025)
 85                         Bank of Baroda (20/02/2025)
 86                            Indian Bank (20/08/2025)
 87   National Bank For Agriculture and Rural Develo...
 88                      HDFC Bank Limited (11/07/2025)
 89                      Axis Bank Limited (05/06/2025)
 90                      Axis Bank Limited (15/07/2025)
 91            Kotak Mahindra Bank Limited (29/01/2025)
 92   National Bank For Agriculture and Rural Develo...
 93                      HDFC Bank Limited (24/06/2025)
 94            Kotak Mahindra Bank Limited (09/05/2025)
 95                            Indian Bank (23/05/2025)
 96            Kotak Mahindra Bank Limited (22/08/2025)
 97                      HDFC Bank Limited (22/08/2025)
 98                      Axis Bank Limited (22/08/2025)
 99            Kotak Mahindra Bank Limited (14/01/2025)
 100                    ICICI Bank Limited (25/07/2025)
 101                                          Sub Total
 102                                      Treasury Bill
 103                     364 Days Tbill (MD 16/01/2025)
 104                     364 Days Tbill (MD 07/08/2025)
 105                     364 Days Tbill (MD 09/01/2025)
 106                                          Sub Total
 107                                              Total
 108                               Reverse Repo / TREPS
 109                  Clearing Corporation of India Ltd
 110                                          Sub Total
 111                                              Total
 112                       Net Receivables / (Payables)
 113                                        GRAND TOTAL
 114                                                NaN
 115                                        Derivatives

        Unnamed: 2  Unnamed: 3 Unnamed: 4  Unnamed: 5 Unnamed: 6 Unnamed: 7  \
 79            NaN         NaN        NaN         NaN        NaN        NaN
 80            NaN         NaN        NaN         NaN        NaN        NaN
 81   INE160A16PF9  CRISIL A1+       6000    28665.27     0.0035   0.075201
 82   INE476A16YY2  CRISIL A1+       6000    28055.28     0.0034     0.0753
 83   INE090AD6162    ICRA A1+       5500    26065.05     0.0032     0.0747
 84   INE692A16GS3     IND A1+       4000    19520.46     0.0024   0.073498
 85   INE028A16EX5     IND A1+       4000       19444     0.0024     0.0735
 86   INE562A16NH7  CRISIL A1+       4000       18742     0.0023    0.07585
 87   INE261F16769  CRISIL A1+       3500    17127.51     0.0021     0.0735
 88   INE040A16FD9    CARE A1+       3500    16529.07      0.002   0.075762
 89   INE238AD6843  CRISIL A1+       3000    14274.09     0.0017    0.07515
 90   INE238AD6868  CRISIL A1+       3000    14154.17     0.0017      0.076
 91   INE237A168V8  CRISIL A1+       2500    12206.35     0.0015   0.073174
 92   INE261F16876  CRISIL A1+       2500    11856.59     0.0014     0.0756
 93   INE040A16FA5  CRISIL A1+       2500    11849.74     0.0014     0.0753
 94   INE237A162X7  CRISIL A1+       2000      9568.6     0.0012     0.0748
 95   INE562A16MZ1  CRISIL A1+       2000     9540.37     0.0012   0.075149
 96   INE237A162Y5  CRISIL A1+       2000     9372.83     0.0011    0.07515
 97   INE040A16FJ6    CARE A1+       2000     9368.04     0.0011   0.075762

In [76]:
df_list = extract_all_raw_tables(df, table_extract_combos)

In [77]:
col_list = ['instrument', 'isin','industry', 'quantity', 'value', 'percentage_of_net_assets','ytm']

In [79]:
df_list[1]

,Unnamed: 0,"Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,instrument_type
35,NaN,Arbitrage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arbitrage
36,NaN,Bajaj Finance Limited,INE296A01024,Finance,372250,28674.42,0.0035,NaN,NaN,NaN,NaN,Arbitrage
37,NaN,Bharat Electronics Limited,INE263A01024,Aerospace & Defense,1117200,3185.14,0.0004,NaN,NaN,NaN,NaN,Arbitrage
38,NaN,IndusInd Bank Limited,INE095A01012,Banks,207500,3003.77,0.0004,NaN,NaN,NaN,NaN,Arbitrage
39,NaN,Bharti Airtel Limited,INE397D01024,Telecom - Services,166250,2842.13,0.0003,NaN,NaN,NaN,NaN,Arbitrage
40,NaN,Tata Motors Limited,INE155A01022,Automobiles,289850,2825.02,0.0003,NaN,NaN,NaN,NaN,Arbitrage
41,NaN,Mahindra & Mahindra Limited,INE101A01026,Automobiles,76300,2361.41,0.0003,NaN,NaN,NaN,NaN,Arbitrage
42,NaN,Hindalco Industries Limited,INE038A01020,Non - Ferrous Metals,306600,2318.51,0.0003,NaN,NaN,NaN,NaN,Arbitrage
43,NaN,Bandhan Bank Limited,INE545U01014,Banks,677600,1346.66,0.0002,NaN,NaN,NaN,NaN,Arbitrage
44,NaN,Biocon Limited,INE376G01013,Pharmaceuticals & Biotechnology,367500,1334.39,0.0002,NaN,NaN,NaN,NaN,Arbitrage
45,NaN,Reliance Industries Limited,INE002A01018,Petroleum Products,41750,1232.94,0.0001,NaN,NaN,NaN,NaN,Arbitrage
46,NaN,NMDC Limited,INE584A01023,Minerals & Mining,346500,848.61315,0.0001,NaN,NaN,NaN,NaN,Arbitrage
47,NaN,Bharat Heavy Electricals Limited,INE257A01026,Electrical Equipment,228375,638.76,0.0001,NaN,NaN,NaN,NaN,Arbitrage
48,NaN,Titan Company Limited,INE280A01028,Consumer Durables,16100,615.66,0.0001,NaN,NaN,NaN,NaN,Arbitrage
49,NaN,DLF Limited,INE271C01023,Realty,66825,598.18,0.0001,NaN,NaN,NaN,NaN,Arbitrage
50,NaN,IDFC Limited,INE043D01016,Finance,480000,543.79,0.0001,NaN,NaN,NaN,NaN,Arbitrage
51,NaN,Hindustan Copper Limited,INE531E01026,Non - Ferrous Metals,124550,428.33,0.0001,NaN,NaN,NaN,NaN,Arbitrage
52,NaN,PI Industries Limited,INE603J01030,Fertilizers & Agrochemicals,5250,244.43,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
53,NaN,Tata Steel Limited,INE081A01020,Ferrous Metals,99000,166.86,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
54,NaN,HDFC Life Insurance Company Limited,INE795G01014,Insurance,19800,142.16,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
55,NaN,Jindal Steel & Power Limited,INE749A01030,Ferrous Metals,8750,90.97,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
56,NaN,Bajaj Finserv Limited,INE918I01026,Finance,4500,88.8,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
57,NaN,Hindustan Unilever Limited,INE030A01027,Diversified FMCG,2700,79.87,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
58,NaN,Larsen & Toubro Limited,INE018A01030,Construction,1200,44.11,$0.00%,NaN,NaN,NaN,NaN,Arbitrage
59,NaN,United Spirits Limited,INE854D01024,Beverages,1400,22.26,$0.00%,NaN,NaN,NaN,NaN,Arbitrage

In [60]:
def rename_columns(df, col_list):
    df.columns = col_list
    return df

In [61]:
def clean_raw_table(df):
    clean_df = (df
                .iloc[:,1:-3]
                .pipe(rename_columns, col_list)
                .query('(~quantity.isnull())|(~ytm.isnull())')
                .assign(
                        quantity = lambda x: x.quantity.astype(float),
                        value = lambda x: x.value.astype(float),
                        percentage_of_net_assets = lambda x: x.percentage_of_net_assets.astype('string').str.replace('$', '').str.replace('%', '').astype(float),
                        ytm = lambda x: x.ytm.astype(float)
                    )
                )
    return clean_df

In [93]:
def clean_all_raw_tables(df_dict):
    clean_df_list = []
    for key,df in df_dict.items():
        try:
            print(key)
            df = clean_raw_table(df).assign(table_name=key)
            clean_df_list.append(df)
        except Exception as e:
            print(e)
            continue
    return clean_df_list

In [54]:
df_list[4]

,Unnamed: 0,"Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
79,NaN,Money Market Instruments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,Certificate of Deposit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,Punjab National Bank (15/05/2025),INE160A16PF9,CRISIL A1+,6000,28665.27,0.0035,0.075201,NaN,NaN,NaN
82,NaN,Canara Bank (02/09/2025),INE476A16YY2,CRISIL A1+,6000,28055.28,0.0034,0.0753,NaN,NaN,NaN
83,NaN,ICICI Bank Limited (27/06/2025),INE090AD6162,ICRA A1+,5500,26065.05,0.0032,0.0747,NaN,NaN,NaN
84,NaN,Union Bank of India (31/01/2025),INE692A16GS3,IND A1+,4000,19520.46,0.0024,0.073498,NaN,NaN,NaN
85,NaN,Bank of Baroda (20/02/2025),INE028A16EX5,IND A1+,4000,19444,0.0024,0.0735,NaN,NaN,NaN
86,NaN,Indian Bank (20/08/2025),INE562A16NH7,CRISIL A1+,4000,18742,0.0023,0.07585,NaN,NaN,NaN
87,NaN,National Bank For Agriculture and Rural Develo...,INE261F16769,CRISIL A1+,3500,17127.51,0.0021,0.0735,NaN,NaN,NaN
88,NaN,HDFC Bank Limited (11/07/2025),INE040A16FD9,CARE A1+,3500,16529.07,0.002,0.075762,NaN,NaN,NaN
89,NaN,Axis Bank Limited (05/06/2025),INE238AD6843,CRISIL A1+,3000,14274.09,0.0017,0.07515,NaN,NaN,NaN
90,NaN,Axis Bank Limited (15/07/2025),INE238AD6868,CRISIL A1+,3000,14154.17,0.0017,0.076,NaN,NaN,NaN
91,NaN,Kotak Mahindra Bank Limited (29/01/2025),INE237A168V8,CRISIL A1+,2500,12206.35,0.0015,0.073174,NaN,NaN,NaN
92,NaN,National Bank For Agriculture and Rural Develo...,INE261F16876,CRISIL A1+,2500,11856.59,0.0014,0.0756,NaN,NaN,NaN
93,NaN,HDFC Bank Limited (24/06/2025),INE040A16FA5,CRISIL A1+,2500,11849.74,0.0014,0.0753,NaN,NaN,NaN
94,NaN,Kotak Mahindra Bank Limited (09/05/2025),INE237A162X7,CRISIL A1+,2000,9568.6,0.0012,0.0748,NaN,NaN,NaN
95,NaN,Indian Bank (23/05/2025),INE562A16MZ1,CRISIL A1+,2000,9540.37,0.0012,0.075149,NaN,NaN,NaN
96,NaN,Kotak Mahindra Bank Limited (22/08/2025),INE237A162Y5,CRISIL A1+,2000,9372.83,0.0011,0.07515,NaN,NaN,NaN
97,NaN,HDFC Bank Limited (22/08/2025),INE040A16FJ6,CARE A1+,2000,9368.04,0.0011,0.075762,NaN,NaN,NaN
98,NaN,Axis Bank Limited (22/08/2025),INE238AD6884,CRISIL A1+,2000,9366.18,0.0011,0.076,NaN,NaN,NaN
99,NaN,Kotak Mahindra Bank Limited (14/01/2025),INE237A163V9,CRISIL A1+,1500,7345.38,0.0009,0.073176,NaN,NaN,NaN
100,NaN,ICICI Bank Limited (25/07/2025),INE090AD6170,ICRA A1+,500,2355.67,0.0003,0.075301,NaN,NaN,NaN
101,NaN,Sub Total,NaN,NaN,NaN,295406.65,0.0359,NaN,NaN,NaN,NaN
102,NaN,Treasury Bill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,364 Days Tbill (MD 16/01/2025),IN002023Z448,Sovereign,30000000,29439.06,0.0036,0.065,NaN,NaN,NaN
104,NaN,364 Days Tbill (MD 07/08/2025),IN002024Z198,Sovereign,10000000,9474.23,0.0011,0.065341,NaN,NaN,NaN
105,NaN,364 Days Tbill (MD 09/01/2025),IN002023Z430,Sovereign,6000000,5895.02,0.0007,0.065,NaN,NaN,NaN
106,NaN,Sub Total,NaN,NaN,NaN,44808.31,0.0054,NaN,NaN,NaN,NaN
107,NaN,Total,NaN,NaN,NaN,340214.96,0.0413,NaN,NaN,NaN,NaN
108,NaN,Reverse Repo / TREPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,NaN,Clearing Corporation of India Ltd,NaN,,NaN,1150220,0.1395,0.066066,NaN,NaN,NaN
110,NaN,Sub Total,NaN,NaN,NaN,1150220,0.1395,NaN,NaN,NaN,NaN
111,NaN,Total,NaN,NaN,NaN,1150220,0.1395,NaN,NaN,NaN,NaN
112,NaN,Net Receivables / (Payables),NaN,NaN,NaN,-321.76,-0.0004,NaN,NaN,NaN,NaN
113,NaN,GRAND TOTAL,NaN,NaN,NaN,8244107.47,1,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,Derivatives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,Name of the Instrument,NaN,Long / Short,Quantity,Market value \n(Rs. in Lakhs),% to AUM,Notes & Symbols,NaN,NaN,NaN

In [96]:
clean_df_list = clean_all_raw_tables(df_dict)

Equity & Equity related
Arbitrage
Equity & Equity related Foreign Investments
Index / Stock Options
Money Market Instruments
Index / Stock Futures

In [123]:
combined_df = pd.concat(clean_df_list).assign(statement_period=statement_period).reset_index(drop=True)

In [124]:
combined_df

,instrument,isin,industry,quantity,value,percentage_of_net_assets,ytm,table_name,statement_period
0,HDFC Bank Limited,INE040A01034,Banks,38717754.0,670610.86,0.0813,NaN,Equity & Equity related,Monthly Portfolio Statement as on September 30...
1,Power Grid Corporation of India Limited,INE752E01010,Power,170268886.0,600793.76,0.0729,NaN,Equity & Equity related,Monthly Portfolio Statement as on September 30...
2,Bajaj Holdings & Investment Limited,INE118A01012,Finance,5276536.0,553756.62,0.0672,NaN,Equity & Equity related,Monthly Portfolio Statement as on September 30...
3,Coal India Limited,INE522F01014,Consumable Fuels,97650994.0,498166.55,0.0604,NaN,Equity & Equity related,Monthly Portfolio Statement as on September 30...
4,ITC Limited,INE154A01025,Diversified FMCG,88311955.0,457588.39,0.0555,NaN,Equity & Equity related,Monthly Portfolio Statement as on September 30...
...,...,...,...,...,...,...,...,...,...
100,Jindal Steel & Power Limited October 2024 Future,NaN,,-8750.0,-91.65,0.0000,NaN,Index / Stock Futures,Monthly Portfolio Statement as on September 30...
101,Bajaj Finserv Limited October 2024 Future,NaN,,-4500.0,-89.53,0.0000,NaN,Index / Stock Futures,Monthly Portfolio Statement as on September 30...
102,Hindustan Unilever Limited October 2024 Future,NaN,,-2700.0,-80.42,0.0000,NaN,Index / Stock Futures,Monthly Portfolio Statement as on September 30...
103,Larsen & Toubro Limited October 2024 Future,NaN,,-1200.0,-44.46,0.0000,NaN,Index / Stock Futures,Monthly Portfolio Statement as on September 30...
104,United Spirits Limited October 2024 Future,NaN,,-1400.0,-22.46,0.0000,NaN,Index / Stock Futures,Monthly Portfolio Statement as on September 30...

In [99]:
combined_df.groupby('table_name').percentage_of_net_assets.sum()

table_name
Arbitrage                                      0.0066
Equity & Equity related                        0.6886
Equity & Equity related Foreign Investments    0.1241
Index / Stock Futures                         -0.0067
Index / Stock Options                          0.0003
Money Market Instruments                       0.1808
Name: percentage_of_net_assets, dtype: float64

In [35]:
get_idx_from_instrument_text(df, derivatives)

np.int64(74)

In [34]:
get_raw_table(df, equity_domestic,arbitrage)

,Unnamed: 0,"Parag Parikh Flexi Cap Fund (An open-ended dynamic equity scheme investing across large cap, mid-cap, small-cap stocks)",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
3,NaN,Equity & Equity related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(a) Listed / awaiting listing on Stock Exchanges,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,HDFC Bank Limited,INE040A01034,Banks,38717754,670610.86,0.0813,NaN,NaN,NaN,NaN
6,NaN,Power Grid Corporation of India Limited,INE752E01010,Power,170268886,600793.76,0.0729,NaN,NaN,NaN,NaN
7,NaN,Bajaj Holdings & Investment Limited,INE118A01012,Finance,5276536,553756.62,0.0672,NaN,NaN,NaN,NaN
8,NaN,Coal India Limited,INE522F01014,Consumable Fuels,97650994,498166.55,0.0604,NaN,NaN,NaN,NaN
9,NaN,ITC Limited,INE154A01025,Diversified FMCG,88311955,457588.39,0.0555,NaN,NaN,NaN,NaN
10,NaN,ICICI Bank Limited,INE090A01021,Banks,33093059,421274.64,0.0511,NaN,NaN,NaN,NaN
11,NaN,Maruti Suzuki India Limited,INE585B01010,Automobiles,3043078,402842.67,0.0489,NaN,NaN,NaN,NaN
12,NaN,HCL Technologies Limited,INE860A01027,IT - Software,18706973,335995.94,0.0408,NaN,NaN,NaN,NaN
13,NaN,Axis Bank Limited,INE238A01034,Banks,23645558,291360.57,0.0353,NaN,NaN,NaN,NaN
14,NaN,Kotak Mahindra Bank Limited,INE237A01028,Banks,13141651,243639.64,0.0296,NaN,NaN,NaN,NaN
15,NaN,Motilal Oswal Financial Services Limited,INE338I01027,Capital Markets,22275986,169765.29,0.0206,NaN,NaN,NaN,NaN
16,NaN,Infosys Limited,INE009A01021,IT - Software,8733754,163810.29,0.0199,NaN,NaN,NaN,NaN
17,NaN,Balkrishna Industries Limited,INE787D01026,Auto Components,4189074,127773.04,0.0155,NaN,NaN,NaN,NaN
18,NaN,Multi Commodity Exchange of India Limited,INE745G01035,Capital Markets,1871649,105940.95,0.0129,NaN,NaN,NaN,NaN
19,NaN,Indian Energy Exchange Limited,INE022Q01020,Capital Markets,44206584,90305.21,0.011,NaN,NaN,NaN,NaN
20,NaN,Central Depository Services (India) Limited,INE736A01011,Capital Markets,6156590,88476.35,0.0107,NaN,NaN,NaN,NaN
21,NaN,Zydus Lifesciences Limited,INE010B01027,Pharmaceuticals & Biotechnology,7678847,82052.32,0.01,NaN,NaN,NaN,NaN
22,NaN,Dr. Reddy's Laboratories Limited,INE089A01023,Pharmaceuticals & Biotechnology,1187695,80188.42,0.0097,NaN,NaN,NaN,NaN
23,NaN,Cipla Limited,INE059A01026,Pharmaceuticals & Biotechnology,4174123,69044.17,0.0084,NaN,NaN,NaN,NaN
24,NaN,IPCA Laboratories Limited,INE571A01038,Pharmaceuticals & Biotechnology,3541831,53060.17,0.0064,NaN,NaN,NaN,NaN
25,NaN,Indraprastha Gas Limited,INE203G01027,Gas,9335026,52140.79,0.0063,NaN,NaN,NaN,NaN
26,NaN,NMDC Limited,INE584A01023,Minerals & Mining,17775934,43535.039959,0.0053,NaN,NaN,NaN,NaN
27,NaN,ICRA Limited,INE725G01011,Capital Markets,422587,30585.58,0.0037,NaN,NaN,NaN,NaN
28,NaN,EID Parry India Limited,INE126A01031,Fertilizers & Agrochemicals,2259531,19381.13,0.0024,NaN,NaN,NaN,NaN
29,NaN,UTI Asset Management Company Limited,INE094J01016,Capital Markets,962555,11929.43,0.0014,NaN,NaN,NaN,NaN
30,NaN,Maharashtra Scooters Limited,INE288A01013,Finance,80159,9413.75,0.0011,NaN,NaN,NaN,NaN
31,NaN,Swaraj Engines Limited,INE277A01016,Industrial Products,47293,1514.49,0.0002,NaN,NaN,NaN,NaN
32,NaN,Accelya Solutions India Limited,INE793A01012,IT - Software,25272,473.17,0.0001,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
get_idx_from_instrument_text(df,equity_domestic)

np.int64(3)

In [13]:
df[df.iloc[:, 1]==equity_domestic].index[0]

np.int64(3)

In [104]:
df[df.astype(str).apply(lambda x: x.str.contains('Monthly Portfolio Statement')).any(axis=1)].dropna(how='all', axis=1).values

array([['Monthly Portfolio Statement as on September 30, 2024']],
      dtype=object)